### PR TITLE
feat: upgrade dependencies

### PR DESCRIPTION
**Pull request by janmichek**
## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by janmichek** [comment]
More ore less the whole app will deserve to go through.
Datepicker component has been upgraded to new major version, so also focus on this, please. @Liubov-crypto

**Comment by janmichek** [comment]
Deployed to https://pr-853-aescan.stg.service.aepps.com/ and https://pr-853-aescan-testnet.stg.service.aepps.com/

**Review by Liubov-crypto — APPROVED** [review]
LGTM. 

I have a question: why I can't see Listed tokens? I see the same on prod: 



https://github.com/user-attachments/assets/0efb87e0-4bc7-4d0f-a4a1-f3195e6036d7

**Comment by janmichek** [comment]
> LGTM.
> 
> I have a question: why I can't see Listed tokens? I see the same on prod:
> 2024-07-19.1.12.01.mov
> 
> 

Thanks, that's a separate issue I am solving with Keno.

**Pull request merged**
