### PR TITLE
feat: Add custom date picker to charts 2

### LINKED ISSUE #499: Add custom date picker to transactions chart
Add custom date picker to transactions chart, native browser date picker.

### LINKED ISSUE #629: Shorten Y axis transactions chart labels
### Please describe the problem that your request should resolve.

Currently the Y axis takes a lot of horizontal space in the mobile view:
image

### Describe the solution you'd like

Values of the Y axis could be shorten using K and M

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #499
resolves #629

## Demo

https://github.com/aeternity/aescan/assets/15363559/636d5691-b351-4242-ba18-99a33441beac

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] Add custom date picker to transactions chart 
- [x] Add custom date picker to contract chart

### CODE REVIEW

**Comment by janmichek** [comment]
Follow the convo in here https://github.com/aeternity/aescan/pull/528

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by michele-franchi** [comment]
@janmichek is this ready to be reviewed?

**Comment by janmichek** [comment]
> @janmichek is this ready to be reviewed?

Still waiting for MDW

**Comment by janmichek** [comment]
also added the number formatting here #629

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Review by michele-franchi — APPROVED** [review]
Looks good

**Pull request merged**
