### PR TITLE
feat: Smart contracts event decoding

### LINKED ISSUE #669: smart contracts event decoding
The Smart Contract verification now allows to decode events of smart contracts in the following table: https://aescan.io/contracts/ct_9cYQVU42y1icb9VEGijUs93xyTbKwmq4d7JhdnTYPZ7rMQhwz?type=events

A research should outline what can be decoded from the logs endpoint, used in the smart contracts event table:
https://mainnet.aeternity.io/mdw/v2/contracts/logs?contract_id=ct_9cYQVU42y1icb9VEGijUs93xyTbKwmq4d7JhdnTYPZ7rMQhwz&aexn-args=true

### PR DESCRIPTION
**Pull request by janmichek**
## Description

resolves #669 

please test both emmiting event from AE Studio and emmiting on contract detail through Write action. 
In the second case, it should refresh the tab, so after Query -> see Events -> should be up to date

## Demo

https://github.com/aeternity/aescan/assets/15363559/0afc3a9f-9c11-4793-9819-303d7b7c26ef

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add ability to show decoded events

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
@janmichek I have checked and deployed all contracts on ae studio but was not able to see field with event emitter. What I'm doing wrong?

**Comment by janmichek** [comment]
Here is the sourece code, but also feel free to test on another examples, please


contract EventEmitter =

    datatype event =
        FirstEvent(int)
        | SecondEvent(address)
        | AnotherEvent(indexed address, string)

    stateful entrypoint emitEvents(value: int, msg: string) =
        Chain.event(FirstEvent(value))
        Chain.event(SecondEvent(Call.caller))
        Chain.event(AnotherEvent(Call.caller, msg))

**Comment by janmichek** [comment]
> @janmichek I have checked and deployed all contracts on ae studio but was not able to see field with event emitter. What I'm doing wrong?

I think you can also use mine previously deployed.

**Comment by Liubov-crypto** [comment]
I tried it again, but it's not working for me. Probably I'm doing something wrong. But it seems that AE studio isn't working correctly, I even can't create a new empty field to put your code there. Have to delete existent one. 

1. I can't paste an example of code into AE studio: 
cry


https://github.com/user-attachments/assets/9e8e78a1-6c56-4ccd-9046-782854b0ba3f

2. Also I was searching for events to do some tx with them, but not working for me.

**Comment by janmichek** [comment]
> I tried it again, but it's not working for me. Probably I'm doing something wrong. But it seems that AE studio isn't working correctly, I even can't create a new empty field to put your code there. Have to delete existent one.
> 
>     1. I can't paste an example of code into AE studio:
>        cry
> 
> 
> 2024-09-05.2.03.19.mov
> 
>     2. Also I was searching for events to do some tx with them, but not working for me.
> 
> 
> 

Try different browser

**Comment by janmichek** [comment]
From your video looks completely fine.
Try open it in private window.

**Pull request merged**
