### PR TITLE
fix: remove unused attempt for account names counter

### PR DESCRIPTION
**Pull request by janmichek**
## Description
Initially I grabbed the issue https://github.com/aeternity/aescan/issues/553
Found out that 
1) Such an endpoint does not exist (requested here https://github.com/aeternity/ae_mdw/issues/1629)
2) There was a wrong attempt to get names count, that was not even implemented (dead code) SO at least I removed the dead code

## Demo
Without any visual change. Should work the same

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] remove attempt to get names count manually

### CODE REVIEW

**Review by Liubov-crypto — APPROVED** [review]
As I understood the name counter isn't implemented yet on middleware's side. Besides that LGTM. 

But I have a question: I noticed that on other pr name counter is working correctly and showing number of names. @janmichek  Correct me if I'm wrong: 

https://github.com/aeternity/aescan/assets/69896204/4b97c25c-edba-4e34-b85c-e0e5d64e3b38

**Comment by janmichek** [comment]
@Liubov-crypto 
Good catch! There was a bug in app.
The count of names was taken from paginated response so it was always maximum of 10.

https://github.com/aeternity/aescan/assets/15363559/5b8dc2ff-93ae-432c-a948-cd75ea6e0255


I removed that field for now, until we resolve it and will be able to show correct number.
Followup here https://github.com/aeternity/aescan/issues/553

**Comment by Liubov-crypto** [comment]
LGTM. AENS Names counter has been removed.

**Review by michele-franchi — APPROVED** [review]
Makes sense, it was counting first page only.

**Pull request merged**
