### PR TITLE
fix: Move time calculation to MDW

### LINKED ISSUE #114: Move time calculation to MDW
### Context information
Some adapters are using block height to calculate time, But some needs to be calculated because there is no time entry in response

### Steps to reproduce

see usage formatBlockDiffAsDatetime in [adapters.js](https://github.com/aeternity/aescan/blob/develop/src/utils/adapters.js)

### What is expected?

Move other calculations to backend, remove `formatBlockDiffAsDatetime()` then

This Issue is followup of https://github.com/aeternity/aescan/issues/100

MDW Tracking https://github.com/aeternity/ae_mdw/issues/831

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves partly #114 

## Demo

https://github.com/aeternity/aescan/assets/15363559/0cb75776-4396-41ca-8a74-a2b146b1acaa

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  

- [x] reuse some usages of approximate time from MDW

### CODE REVIEW

**Comment by janmichek** [comment]
It has been resolved partly some responses from MDW still need to be calculated on FE.
I proposed the remaining responses in here
https://github.com/aeternity/ae_mdw/issues/831#issuecomment-1609530179

The issue should not be closed after merging this PR

**Review by lukeromanowicz — APPROVED** [review]
Nice improvement. Looks and works great :)

**Review by michele-franchi — APPROVED** [review]
It looks good to me but I'm wondering if any hint should be updated.
I see the property is called `approximate_expire_time` which seems to be an estimate so I guess nothing should be done.

**Comment by janmichek** [comment]
> It looks good to me but I'm wondering if any hint should be updated. I see the property is called `approximate_expire_time` which seems to be an estimate so I guess nothing should be done.

I have been checking this in the Hints Revision PR which ones are exact and which ones are estimated. All should be aligned correctly

**Review by CharisSiarampalis — APPROVED** [review]

**Pull request merged**
