### PR TITLE
feat: upgrade node version to v20

### PR DESCRIPTION
**Pull request by janmichek**
## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] I have updated the documentation accordingly.
- [x] upgrade node version on deployment servers

### CODE REVIEW

**Comment by janmichek** [comment]
@Liubov-crypto The whole app needs to be tested. See if there are no console errors
@michele-franchi you can upgrade your local node version

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
1. Account info, bring me such errors in console: 


2.  Tokens page are not uploading info: 

https://github.com/aeternity/aescan/assets/69896204/794749a3-48a0-4a9c-9a25-3e66fc89abf9

**Comment by janmichek** [comment]
> 1. Account info, bring me such errors in console:
>        
> 
>     2. Tokens page are not uploading info:
>        
>        https://github.com/aeternity/aescan/assets/69896204/794749a3-48a0-4a9c-9a25-3e66fc89abf9

Thanks for reporting. The root cause for those 2 symptoms is the same. For different deployments there is different url. I reported to Petar. Let's see...

**Comment by janmichek** [comment]
@Liubov-crypto it has been fixed by Petar. You can continue on testing

**Comment by Liubov-crypto** [comment]
In general LGTM. Previous errors from console have been fixed. 

Found this one: 


however no visible errors in UI.

**Comment by janmichek** [comment]
> In general LGTM. Previous errors from console have been fixed.
> 
> Found this one: 
> 
> however no visible errors in UI.

Thank you, this is a occasional known issue described in here https://github.com/aeternity/aescan/issues/284

**Review by michele-franchi — APPROVED** [review]
Looks good

**Pull request merged**
