### PR TITLE
feat: Transaction stats 2

### LINKED ISSUE #447: Transactions stats
Along with charts we could elaborate some ideas to display the following stats, in the [transactions page](https://aescan.io/transactions):
- Total transactions (with live increase)
- Last day transactions (with live increase)

to make the transactions page less static.

### PR DESCRIPTION
**Pull request by janmichek**
## Description
Resolves #447

## Demo
image
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add transactions stats

### CODE REVIEW

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
It seems that TRANSACTIONS IN LAST 24H is not updating at all: 

https://github.com/aeternity/aescan/assets/69896204/bf1bcc6e-9b08-4990-8404-3be0a0eb880d

@janmichek please check it. 

Also I found additional issue with zoom on mobile, will register it separately cuz it's also reproducible on product.

**Comment by janmichek** [comment]
> It seems that TRANSACTIONS IN LAST 24H is not updating at all

Interesting, I cannot confirm the same issue. Maybe there was some downtime at the moment you were reviewing it. If it appears repeatedly, I will investigate and report it.

**Comment by Liubov-crypto** [comment]
> > It seems that TRANSACTIONS IN LAST 24H is not updating at all
> 
> Interesting, I cannot confirm the same issue. Maybe there was some downtime at the moment you were reviewing it. If it appears repeatedly, I will investigate and report it.

@janmichek still not working for me, I've tried in different browsers. Also no visible issues in console.

**Comment by michele-franchi** [comment]
@Liubov-crypto could you check again?

**Review by Liubov-crypto — APPROVED** [review]
Now, it's working, LGTM

**Comment by janmichek** [comment]
improvement followup, noticed after the merge https://github.com/aeternity/aescan/issues/646

**Pull request merged**
