### PR TITLE
fix: Account tabs overflow

### LINKED ISSUE #548: Account tabs overflow
### Context information

application version: 
device: Samsung S22
browser: Firefox
operating system: Android 14

### Steps to reproduce

view account in the narrowest resolution (320px

### What is actually happening?
image

### PR DESCRIPTION
**Pull request by janmichek**
## Description
Resolves #548 

I got inspiration from referenced explorers

## Demo
https://github.com/aeternity/aescan/assets/15363559/b85e4eae-0fc8-489c-8969-b02102f6329a

## Checklist:
- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add scrollbar to tabs

### CODE REVIEW

**Review by michele-franchi — COMMENTED** [review]
It looks good but is it possible to hide the scrollbar?

**Comment by janmichek** [comment]
> It looks good but is it possible to hide the scrollbar?

I think it is possible, but would not recommend it. The reference explorers show it as well. Now its a bit messy with the tabs design, but that's something we want to change.

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Review by michele-franchi — COMMENTED** [review]
It looks good to me but it seems to not be aligned with dev, I see some files regarding pipelines and version. Could you fix it? @janmichek

**Comment by janmichek** [comment]
> It looks good to me but it seems to not be aligned with dev, I see some files regarding pipelines and version. Could you fix it? @janmichek

I aligned with dev. Seems like I forgot to force push after rebase, I did just a push. It's just about more files in Diff. If you want me to make the diff clear, I can adjust it.

**Comment by michele-franchi** [comment]
> > It looks good to me but it seems to not be aligned with dev, I see some files regarding pipelines and version. Could you fix it? @janmichek
> 
> I aligned with dev. Seems like I forgot to force push after rebase, I did just a push. It's just about more files in Diff. If you want me to make the diff clear, I can adjust it.

I would make it clear, to avoid potential issues.

**Comment by janmichek** [comment]
Cleaner solution moved here https://github.com/aeternity/aescan/pull/601

**Pull request closed without merging**
