### PR TITLE
fix: Zoom is applied on Transaction page on mobile

### LINKED ISSUE #638: Zoom is applied on Transaction page on mobile
### Context information

application version: ÆSCAN VERSION [v0.10.0](https://github.com/aeternity/aescan/releases)
device: iPhone 13
browser: Safari 17.2.1
operating system: iOS

### Steps to reproduce
1. Go to Transactions page, 
2. Select different types of Tx
3. Observe zoom

### What is expected?
Shouldn't be zoomed. 

### What is actually happening?

https://github.com/aeternity/aescan/assets/69896204/f45d880e-fdc3-4e1c-b20a-39f82a162770

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #638

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] possible fix safari zooming issue

### CODE REVIEW

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
Still reproducible for me.

**Comment by michele-franchi** [comment]
I also confirm the issue is still there. I think it's because the font size of the values inside the dropdown is still < 16px.

**Review by michele-franchi — COMMENTED** [review]
I also confirm the issue is still there. I think it's because the font size of the values inside the dropdown is still < 16px.

**Comment by janmichek** [comment]
> I also confirm the issue is still there. I think it's because the font size of the values inside the dropdown is still < 16px.

Thanks for the hint. I found one more place intentionally affecting this, so I tried a different approach. If it's not gonna work, then I will use your suggestion. Please help me to check again

**Review by Liubov-crypto — APPROVED** [review]
Fixed, LGTM

**Review by michele-franchi — APPROVED** [review]
Works well now

**Pull request merged**
