### PR TITLE
feat: Migrate to v3 part

### PR DESCRIPTION
**Pull request by janmichek**
## Description
another part of migration endoints
when testing, focus on account tokens listing and token events counter, nft detail
partly resolves https://github.com/aeternity/aescan/issues/690

## Demo
Should work without any change

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
I found some strange displaying of activities here: https://pr-887-aescan.stg.service.aepps.com/accounts/ak_fURxL4TQ3jSGvhpEzZeS7szmmNbiMwtDnUtfwRf3AqqPexXyK?type=activities 

na

and here: https://pr-887-aescan-testnet.stg.service.aepps.com/accounts/ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688?type=activities 

th

is this correct displaying? https://pr-887-aescan-testnet.stg.service.aepps.com/tokens/ct_Sn3iTuEXniEAAiojffR5nmigCffQZwy3sNVHG6Zxof8HeNXXv?type=events


md

@janmichek  could you check it please?

**Comment by janmichek** [comment]
@Liubov-crypto 

1.
> I found some strange displaying of activities here: https://pr-887-aescan.stg.service.aepps.com/accounts/ak_fURxL4TQ3jSGvhpEzZeS7szmmNbiMwtDnUtfwRf3AqqPexXyK?type=activities

I was checking this. It's even problem in production, so not related to the change itself.
I reported this to MDW. 

2.
> and here: https://pr-887-aescan-testnet.stg.service.aepps.com/accounts/ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688?type=activities

I don't see any suspicious on that. Also looks the same as on production

**Review by Liubov-crypto — APPROVED** [review]
the rest is LGTM

**Comment by janmichek** [comment]
Thanks will be released in the second release

**Pull request merged**
