### PR TITLE
fix: UI fixes

### PR DESCRIPTION
**Pull request by janmichek**
## Description

fixes https://github.com/aeternity/aescan/issues/910
fixes https://github.com/aeternity/aescan/issues/854

- improved github output
- replace --- for 'N/A'
- remove duplicate ae logo
- fetchTokenHoldersCount optimization
- floor line chart to minimum value of 0 so -1 is not visible on Y axis
- header STATE CHANNELS -> LATEST ACTIVE STATE CHANNELS
- make Tabs semi transparent
- highlight table row on hover

## Checklist:

- [x] Measure performance after removing booster

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Small bugs:

1. question mark is shifted: 

https://github.com/user-attachments/assets/8b343bbb-4f04-4d96-ab86-f466453c5f19

2. Line on chart is cropped: 

https://github.com/user-attachments/assets/1989e4b6-a10b-4724-a4a7-c4b7104ce895

3. Double AE labels and data is shifted: 


https://github.com/user-attachments/assets/6f7a86d5-e316-4688-97c7-cd5b8c651698


ae

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
@janmichek please check my comments above.

**Comment by janmichek** [comment]
@Liubov-crypto 1,3 fixed
2 - Good catch! That unfortunately how the chart prints. I would say it's good enough

**Comment by Liubov-crypto** [comment]
I found that we show more symbols after full stop, for example here: https://pr-934-aescan.stg.service.aepps.com/state-channels/ch_2VfzXmCRZepB3ichPf3WTt2uf8zMqsyY3cZWg8k1vt3xcu8L8V and in this case some data is showing in second row. Are this acceptable? 


https://github.com/user-attachments/assets/faf7eed7-30a5-4a64-bf37-569e04afd018

The rest is fixed, LGTM

**Review by Liubov-crypto — APPROVED** [review]

**Comment by janmichek** [comment]
@Liubov-crypto yeah that was wrong. I overlooked that, thanks. It's fixed now. Can you check it again, please?

**Review by Liubov-crypto — APPROVED** [review]
Now it's fixed, LGTM

**Comment by janmichek** [comment]
all good just need to open it in new PR before the merge to perform some checks. It's failing here

**Pull request closed without merging**
