### PR TITLE
feat: Add ISC license

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves https://github.com/aeternity/smart-contract-verifier/issues/55

## Demo

image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] Add ISC license

### CODE REVIEW

**Review by Liubov-crypto — APPROVED** [review]
lgtm,

but @janmichek  could you please send me some example of contract for verification with this license? 

thanks!

**Comment by Liubov-crypto** [comment]
Smart Contracts verification doesn't work with ISC license:
https://github.com/aeternity/aescan/assets/69896204/fc3a4e57-1753-4a69-bc26-075098f650ae

or am I doing something wrong?

**Comment by janmichek** [comment]
added on verifier side https://github.com/aeternity/smart-contract-verifier/pull/56

**Comment by janmichek** [comment]
It works for me now. You can retry @Liubov-crypto

**Comment by Liubov-crypto** [comment]
Tested on testnetwork, works fine. LGTM

**Review by michele-franchi — APPROVED** [review]
LGTM

**Pull request merged**
