### PR TITLE
fix: nft template listing

### PR DESCRIPTION
**Pull request by janmichek**
## Demo

https://github.com/aeternity/aescan/assets/15363559/ac158a07-659e-454c-91cf-537267d6ed9f

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] fix nft template listing

### CODE REVIEW

**Review by michele-franchi — COMMENTED** [review]
I'm wondering why the values are always empty? Did you investigate it?

**Comment by janmichek** [comment]
> I'm wondering why the values are always empty? Did you investigate it?

Not really as I wanted to fix it quickly. I created a followup here https://github.com/aeternity/aescan/issues/793

**Review by michele-franchi — APPROVED** [review]
Looks good but should investigate why edition is null in the followup.

**Review by Liubov-crypto — APPROVED** [review]
lgtm

**Pull request merged**
