### PR TITLE
fix: Name fee is empty

### LINKED ISSUE #727: Name fee is empty
### Context information

application version: 
device: 
browser: 
operating system: 

### Steps to reproduce
See https://github.com/aeternity/aescan/pull/724#issuecomment-2057000888

### What is expected?
Fees are displayed correctly.

### What is actually happening?

See https://github.com/aeternity/aescan/pull/724#issuecomment-2057000888.

### PR DESCRIPTION
**Pull request by janmichek**
## Description

resolves #727 

Not sure why it stopped working now. I believe all was working before, there has not been any change in files for a year.

## Demo

https://github.com/aeternity/aescan/assets/15363559/2f936ea6-ab6d-4947-a8a6-89f4f9d3b063

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)

### CODE REVIEW

**Comment by michele-franchi** [comment]
@janmichek to me it sounds something got removed from the mdw endpoint so I would first investigate that with them also to understand if fee / name fee are equal.

**Comment by janmichek** [comment]
> @janmichek to me it sounds something got removed from the mdw endpoint so I would first investigate that with them also to understand if fee / name fee are equal.

Question raised here https://aeternity-workspace.slack.com/archives/C04K21DM61L/p1713356209778889

**Review by Liubov-crypto — APPROVED** [review]
Lgtm

**Comment by michele-franchi** [comment]
@janmichek solution: the fee box should be hidden if `nameFee` is not available

**Comment by janmichek** [comment]
> @janmichek solution: the fee box should be hidden if `nameFee` is not available

fixed

**Review by michele-franchi — APPROVED** [review]
LGTM

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Pull request merged**
