### PR TITLE
feat: Prepend token symbol 

### LINKED ISSUE #396: Prepend token symbol
### Please describe the problem that your request should resolve.
Token related values could be more UX friendly

### Describe the solution you'd like
image

### Additional context
Implement all over the app

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #396 

## Demo

https://github.com/aeternity/aescan/assets/15363559/250803b8-0d3b-4f2d-8ed8-4faddeed4a0a

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add price label component and reuse over app

### CODE REVIEW

**Comment by janmichek** [comment]
Opened a new PR. It has already been approved by Liubov here https://github.com/aeternity/aescan/pull/637 Please take a look at the notes there @michele-franchi

**Comment by Liubov-crypto** [comment]
Could you please add links for testing?

**Comment by janmichek** [comment]
> Could you please add links for testing?

Aha, it didn't produce any links
Here u go

https://pr-809-aescan-testnet.stg.service.aepps.com/
https://pr-809-aescan.stg.service.aepps.com/

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
1. I can't see % for some reason: 

per

2. is this expected that there is no listed tokens?

**Comment by janmichek** [comment]
> 1. I can't see % for some reason:
> 
> 
> per
> 
>     2. is this expected that there is no listed tokens?
> 
> 
> lis 

Good catch, all fixed now

**Pull request merged**
