### PR TITLE
feat: Add custom date picker to charts

### LINKED ISSUE #499: Add custom date picker to transactions chart
Add custom date picker to transactions chart, native browser date picker.

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #499

## Demo
firefox_P9vR22vMBd

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] Add custom date picker to transactions chart 
- [x] Add custom date picker to contract chart

### CODE REVIEW

**Comment by michele-franchi** [comment]
@janmichek is this ready to be reviewed?

**Comment by janmichek** [comment]
> @janmichek is this ready to be reviewed?

Not yet, pinged the status on Slack

**Comment by Liubov-crypto** [comment]
@janmichek  I have questions: 
1. I have to click twice or press enter button to see info of choose date, is this behaviour correct?
https://github.com/aeternity/aescan/assets/69896204/cae356ef-4ec1-462a-a0b6-dfd440b5429f

2. If I choose a custom date and then refresh the page I will be redirected to the previous page, is this correct? 
https://github.com/aeternity/aescan/assets/69896204/d646a318-d059-41e2-b2dc-0bf5aff35406

**Comment by Liubov-crypto** [comment]
> > I have to click twice or press enter button to see info of choose date, is this behaviour correct?
> 
> FIxed
> 
I have retested and it seems to be broken - I can't choose desired single date, it doesn't respond on my clicks.  
Also, the custom section looks like muted in Safari and Chrome browsers: 

https://github.com/aeternity/aescan/assets/69896204/cda49e54-c0db-4634-8eac-53d6f90e1cdc

@janmichek please check it.

**Comment by janmichek** [comment]
> > > I have to click twice or press enter button to see info of choose date, is this behaviour correct?
> > 
> > 
> > FIxed
> 
> I have retested and it seems to be broken - I can't choose desired single date, it doesn't respond on my clicks. Also, the custom section looks like muted in Safari and Chrome browsers:
> 2023-11-07.1.23.53.mov
> 
> @janmichek please check it.



> > > I have to click twice or press enter button to see info of choose date, is this behaviour correct?
> > 
> > 
> > FIxed
> 
> I have retested and it seems to be broken - I can't choose desired single date, it doesn't respond on my clicks. Also, the custom section looks like muted in Safari and Chrome browsers:
> 2023-11-07.1.23.53.mov
> 
> @janmichek please check it.

I fixed the disabled-like button and found some data inconsistencies.
Ad selectability: I set the controls like this intentionally. As from basis of range picker - you should only select range. Single day data are still available when you hover on the points of chart.

**Review by Liubov-crypto — APPROVED** [review]
As I understood the single day data are available when user hover on the points of chart. In that case, fixed, LGTM.

**Comment by janmichek** [comment]
> As I understood the single day data are available when user hover on the points of chart. In that case, fixed, LGTM.

Thank you. For the merge we still need to wait for mdw deployment. Then I change te URL to mainnet

**Comment by janmichek** [comment]
Tracking:

https://mainnet.aeternity.io/mdw/v3/statistics/transactions?min_start_date=2023-11-01&max_start_date=2023-11-02&limit=1000
(if this URL works, we can change the URL and merge it)

**Comment by janmichek** [comment]
Was just checking this. Still not resolved on MDW side

**Comment by janmichek** [comment]
This needed to be reopen to make the build working Let's continue here https://github.com/aeternity/aescan/pull/611

**Pull request closed without merging**
