### PR TITLE
fix: Older button becomes broken in payingfor tx + UI fixes

### LINKED ISSUE #706: Older button becomes broken in PayingforTx
### Context information

application version: [v0.11.0](https://github.com/aeternity/aescan/releases)
device: Mac
browser: Chrome v.123
operating system: MacOS Monterey 12.7.4

### Steps to reproduce

1. Go to https://aescan.io/transactions?txType=paying_for  

2. User Older button to see oldest Tx 

3. Page is becoming broken on 3rd step 

### What is actually happening?

https://github.com/aeternity/aescan/assets/69896204/387ed276-3923-4245-b108-b2a437a646a5

slice rror

### PR DESCRIPTION
**Pull request by janmichek**
## Description
fixes #706 

I also added 3 more UI small fixes not related to this

## Demo

https://github.com/aeternity/aescan/assets/15363559/55aedf38-18ad-4f82-98ef-1fd85ee7cfeb

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] sanitize missing value of PayingForTx
- [x] fix chip size in paying for TX
- [x] fix collapsible UI of Oracle response
- [x] extend active clicking area of navigation

### CODE REVIEW

**Comment by janmichek** [comment]
BEFORE:

https://github.com/aeternity/aescan/assets/15363559/840affdb-4773-4fd5-940e-db334f5b8aa2


AFTER:

https://github.com/aeternity/aescan/assets/15363559/1e6910cd-9e3e-48c5-a184-3b5cf7865b9e



oracles/ok_2KnfrVbHzdKZLK6YgJ61ybyK8wdYwyr4DwcPPZgyii7WJk6zP1

**Comment by janmichek** [comment]
BEFORE:
image


AFTER: 
image

transactions/th_2FeUZBktAd4a9Lnmei1Ngca9WZ5DBHs48XJNxm4kHsEyDwKuAm

**Comment by janmichek** [comment]
BEFORE:


https://github.com/aeternity/aescan/assets/15363559/52867ed9-f8be-4897-bdaf-11681326b3c9


AFTER:


https://github.com/aeternity/aescan/assets/15363559/9ddfc947-6a42-4660-b3b4-b108d4617b35

**Review by michele-franchi — APPROVED** [review]
Looks good to me

**Pull request merged**
