### PR TITLE
feat: internal Chain.spend values

### LINKED ISSUE #699: internal Chain.spend values
### Please describe the problem that your request should resolve.
 looks weird in aescan for the receivers https://aescan.io/accounts/ak_MAp9r1m6jP7P7ncexacy7VTtjCcDJufqPY4cn5QwtmEKf6N7U?type=activities

### Describe the solution you'd like
display price

### Is it already possible to achieve the same outcome in any other way? If so, how?
no

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #699

## Demo
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] display price value for internal Chain.spend

### CODE REVIEW

**Comment by thepiwo** [comment]
Could we also show the function name of the internal call, e.g. `Chain.spend`?

**Comment by janmichek** [comment]
> Could we also show the function name of the internal call, e.g. `Chain.spend`?

It's already there @thepiwo https://pr-700-aescan.stg.service.aepps.com/accounts/ak_MAp9r1m6jP7P7ncexacy7VTtjCcDJufqPY4cn5QwtmEKf6N7U?type=activities

**Review by thepiwo — APPROVED** [review]

**Review by Liubov-crypto — COMMENTED** [review]
LGTM. 

Is this expected view? 

trs

**Comment by janmichek** [comment]
> LGTM.
> 
> Is this expected view?
> 
> trs

Yeah I think so. What is the address so I can verify It?

**Review by michele-franchi — APPROVED** [review]
Works great

**Pull request merged**
