### PR TITLE
fix: Layout fix

### PR DESCRIPTION
**Pull request by janmichek**
## Description
Unrelated to issue. Just a quick fix of a visible bug

## Demo
Before / after
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] force footer bottom

### CODE REVIEW

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
@janmichek  for me nothing changed, looks as in before version:
https://github.com/aeternity/aescan/assets/69896204/c85968bd-9d4c-4332-a987-6e0eae33f5f6

is this correct?

**Comment by janmichek** [comment]
> @janmichek for me nothing changed, looks as in before version: https://github.com/aeternity/aescan/assets/69896204/c85968bd-9d4c-4332-a987-6e0eae33f5f6
> 
> is this correct?

There was a problem with the footer. The footer was not on the bottom of the screen on the pages with a lot of white space. You can imitate the behavior of the big screen by zooming out in the browser.

**Comment by Liubov-crypto** [comment]
I tried to play with zooming and only when I have reached 30% it changed the footer placement. Is this act as expected? 

https://github.com/aeternity/aescan/assets/69896204/4c03e297-c8be-4980-83cb-79f907b2dcae

**Review by michele-franchi — APPROVED** [review]
Looks good 👌

**Pull request merged**
