### PR TITLE
fix: Fix border and select checkboxes

### LINKED ISSUE #306: Fix border and select checkboxes
### Context information

application version: 
device: 
browser: 
operating system: 

### What is expected?
- Checkboxes are not visible
- The first item should not have a rounded border

### What is actually happening?

image

### PR DESCRIPTION
**Pull request by janmichek**
## Description
fixes #306 

## Demo

https://github.com/aeternity/aescan/assets/15363559/2679fa63-4475-43d2-a43d-efe43e3f6d79

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] fix select styles

### CODE REVIEW

**Comment by janmichek** [comment]
Still not very satisfied with the overall interaction styles. The contras of selected item is too low

**Review by lukeromanowicz — APPROVED** [review]
I agree the color scheme is still not ideal due to insufficient contrast, but still, it's much better without the misleading icon suggesting it's a multiselect. Nice job, thanks for improving it :rocket: 

Side note: check-square and square icons are not used anymore. Perhaps we should consider removing them from the project

**Comment by janmichek** [comment]
> I agree the color scheme is still not ideal due to insufficient contrast, but still, it's much better without the misleading icon suggesting it's a multiselect. Nice job, thanks for improving it 🚀
> 
> Side note: check-square and square icons are not used anymore. Perhaps we should consider removing them from the project

Agree, unused icons removed

**Comment by janmichek** [comment]
Followup https://github.com/aeternity/aescan/issues/320

**Review by michele-franchi — APPROVED** [review]
Looks good, thanks for fixing it.

**Review by CharisSiarampalis — APPROVED** [review]

**Pull request merged**
