### PR TITLE
fix: Improve transaction stats loading

### LINKED ISSUE #646: Improve transaction stats loading
### Please describe the problem that your request should resolve.
The loading concept is not used consistently here. I noticed after I merged https://github.com/aeternity/aescan/pull/618/

### Describe the solution you'd like
to signalize the loading of transaction stats to users more cleanly and consistently. Also check if it loads on SSR correctly

### Is it already possible to achieve the same outcome in any other way? If so, how?
The loading works, but it could be done better.

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolve #646

## Demo

https://github.com/aeternity/aescan/assets/15363559/6730339e-d756-49c2-8275-76c5ad9b8d7e

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] fix transaction loading
- [x] fix content jumping of footer

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
It trows 404 error in Chrome. Also I got 404 error in Safari and Firefox from time to time.

**Comment by michele-franchi** [comment]
Works now @Liubov-crypto

**Review by michele-franchi — APPROVED** [review]
Looks good to me

**Comment by Liubov-crypto** [comment]
LGTM

**Pull request merged**
