### PR TITLE
feat: Upgrade all dependencies 5

### LINKED ISSUE #911: Upgrade all dependencies
### Please describe the problem that your request should resolve.

- [x] try to remove booster

### PR DESCRIPTION
**Pull request by janmichek**
## Description
fixes #911 

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
1. 404 error for the testnet: 


2. A little bit strange aligning here, but the same is on prod: 

https://pr-989-aescan.stg.service.aepps.com/accounts/ak_tnCnNUtytRD3CrQWmr77hCZwAzBPRpcnFjbemhk5xmRoD3EvN?type=activities

https://github.com/user-attachments/assets/7b3bc064-933c-461c-97b6-04a4a2f0c118

3. Percentage of WAE token is absent compared to prod: 

p

**Comment by janmichek** [comment]
> 1. 404 error for the testnet:
>        
> 
>     2. A little bit strange aligning here, but the same is on prod:
> 
> 
> https://pr-989-aescan.stg.service.aepps.com/accounts/ak_tnCnNUtytRD3CrQWmr77hCZwAzBPRpcnFjbemhk5xmRoD3EvN?type=activities
> 2024-11-13.12.55.13.mov
> 
>     3. Percentage of WAE token is absent compared to prod:
> 
> 
> p

Thanks Liubov,
1. that was probably some downtime when buildng, try again pls
2. yes its dense, I will let it pass like this
3. fixed

Can I ask you to test again features that requires user wallet connection? There was a massive upgrade.

**Comment by Liubov-crypto** [comment]
The issues has been fixed. 

I've tried to verify some smart contracts https://pr-989-aescan-testnet.stg.service.aepps.com/contracts/ct_2sWELPZNeGYsg5W1h9GqkXS1bWWm5YwZRhjQr1iznEKpSHQvUt 

but for the some reason was not able to do it. Could you check it please? 
sm

nf

**Comment by janmichek** [comment]
> The issues has been fixed.
> 
> I've tried to verify some smart contracts https://pr-989-aescan-testnet.stg.service.aepps.com/contracts/ct_2sWELPZNeGYsg5W1h9GqkXS1bWWm5YwZRhjQr1iznEKpSHQvUt
> 
> but for the some reason was not able to do it. Could you check it please? sm
> 
> nf

I tried that and was ok. The contract you linked was not deployed. Looks good now, thanks.

**Pull request merged**
