### PR TITLE
fix: Only up to four transactions can be displayed on the dashboard

### LINKED ISSUE #245: Only up to four transactions can be displayed on the dashboard
### Context information

application version: pr-244
device: Samsung Galaxy S22
browser: Every Browser
operating system: Android
### Steps to reproduce
1.Open https://pr-244-aescan.stg.aepps.com/ and go to the dashboard
2.Scroll down the page and go to microblocks
3.Find one microblock that has more than four transactions
4.Click on it
### What is expected?
All transactions are able to be seen
### What is actually happening?
It only displays four transactions. Even the text above them says that there are only four transactions in this microblock.
microblocks

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #245

## Demo

https://github.com/aeternity/aescan/assets/15363559/8c30d9ea-4c52-425d-85c6-2a7336d14144

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] fix counter

### CODE REVIEW

**Comment by lukeromanowicz** [comment]
My understanding of the issue was that even if there are more than 4 transactions in the microblock - you can't browse through all of them. Anyway, I'm not sure it's worth fixing at this point since I am in the process of reverting the whole websocket-based data fetching for that blockchain panel in task #292

**Comment by CharisSiarampalis** [comment]
@janmichek I had a video uploaded for this. But this issue was about the Transactions in this block number. 
image
I t displays at most 4 even if there are more transactions inside the microblock.

**Comment by janmichek** [comment]
> @janmichek I had a video uploaded for this. But this issue was about the Transactions in this block number. image I t displays at most 4 even if there are more transactions inside the microblock.

Thanks for the clarification, that's what I fixed .) You can continue in review @lukeromanowicz

**Review by lukeromanowicz — APPROVED** [review]
My misunderstanding then, LGTM :+1:

**Review by CharisSiarampalis — APPROVED** [review]

**Pull request merged**
