### PR TITLE
feat: show hint if AENS name is in revoked state 2

### LINKED ISSUE #454: show hint if AENS name is in revoked state
### Please describe the problem that your request should resolve.
When an AENS name is revoked actively or expires, it enters in a revoked state for a certain time period (not sure how long exactly, need to look up).

During this time period, an AENS name cannot be claimed again and currently this information is not exposed to the public.

### Describe the solution you'd like
IMO, aeScan should display a hint about the revoked state on following pages:
- Names (Tab: Expired)
- Name details

### Is it already possible to achieve the same outcome in any other way? If so, how?
no

### Additional context
n/a

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #454

## Demo

https://github.com/aeternity/aescan/assets/15363559/0259fed4-7a4b-4ce3-ab1f-32260405cdd5

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] Add conditional hint for revoked state

### CODE REVIEW

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
if I click on Next button to see other expires names the page becomes uploading status forever. The same issue is on product.

https://github.com/aeternity/aescan/assets/69896204/801e3fdc-9b57-44ac-804a-0bdec71ebe5f

unc

I found additional issue on product, when I click on next button to see other In-auction names the previous button becomes unavailable. But maybe this is middleware issue? 
if not, I will register it separately. 

https://github.com/aeternity/aescan/assets/69896204/f7ec8918-5f6b-4ab4-b404-8890f36ba3f1

@janmichek please check it.

**Comment by janmichek** [comment]
> if I click on Next button to see other expires names the page becomes uploading status forever. The same issue is on product.
> 2023-12-11.4.42.00.mov
> 
> unc
> 


Hmm, interesting. I tried the same scenario without any probs. Maye there was some server downtime at that moment? Can I ask you to try again today?


> I found additional issue on product, when I click on next button to see other In-auction names the previous button becomes unavailable. But maybe this is middleware issue? if not, I will register it separately.
> 2023-12-11.4.46.37.mov
> 
> @janmichek please check it.

Yes, I confirm this issue. WIll solve it separately. Good finding, thanks

**Comment by Liubov-crypto** [comment]
@janmichek I have a question: I can see some names in both tabs - Expired and In Auction, for example 77.chain and public.chain.  Is this expected?

**Comment by Liubov-crypto** [comment]
https://github.com/aeternity/aescan/assets/69896204/16abfaa4-00a7-41b1-a062-47dbc7c28578

**Comment by janmichek** [comment]
Thanks, should not be like that. I will check and possibly fix

**Comment by janmichek** [comment]
> 2023-12-12.5.05.14.mov

Followup https://github.com/aeternity/aescan/issues/621

**Review by Liubov-crypto — APPROVED** [review]
LGTM, except the issues that I found and they should be fixed separately.

**Review by michele-franchi — APPROVED** [review]
Looks good

**Pull request merged**
