### PR TITLE
feat: Dashboard loading indicators 3

### LINKED ISSUE #392: Dashboard loading indicators
Implement loading indicator in the dashboard.

### PR DESCRIPTION
**Pull request by janmichek**
## Description
fixes #392 

## Demo

firefox_Cf2yGh6u6V

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  

- [x] add loading to dashboard

### CODE REVIEW

**Review by michele-franchi — COMMENTED** [review]
For some reason I just see a white panel, is it just me?

image

**Comment by janmichek** [comment]
> For some reason I just see a white panel, is it just me?
> image

My bad, fixed

**Review by michele-franchi — CHANGES_REQUESTED** [review]
Now it looks good but I think one loader is still missing. If I simulate a slow connection I get the following blank panel in the blocks section:

image

**Review by michele-franchi — APPROVED** [review]
Good job 👏

**Review by lukeromanowicz — APPROVED** [review]
Nice job :ok_hand:

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Pull request merged**
