### PR TITLE
feat: add microblocks transactions filtering

### LINKED ISSUE #398: Add Microblock transaction filtering
### Please describe the problem that your request should resolve.
Add filter select and filtered result to the Microblock Transactions table

### Describe the solution you'd like
The same as in Account transactions

### Is it already possible to achieve the same outcome in any other way? If so, how?
No, waiting for MDW https://github.com/aeternity/ae_mdw/issues/1471

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #398 

I was testing on mh_QzEw8iHQoZN5wNYNV2ZhXDXnHv1juNrazX8y2Vw9Nh5HFgLqg but better find another one .)

## Demo
https://github.com/aeternity/aescan/assets/15363559/ecf3a56c-9001-45e5-8837-38c18cbc2d91

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add filtering to macroblock txs

### CODE REVIEW

**Comment by janmichek** [comment]
Currently on hold. The url to counter is unclear https://github.com/aeternity/ae_mdw/issues/1471#issuecomment-1785173386

**Comment by janmichek** [comment]
Created followup https://github.com/aeternity/aescan/issues/563

**Review by Liubov-crypto — APPROVED** [review]
I tried with different micro blocks that contains 2 or more transactions, working good to me. LGTM.

**Review by michele-franchi — APPROVED** [review]
Looks good

**Pull request merged**
