### PR TITLE
fix: nfts ordering

### PR DESCRIPTION
**Pull request by janmichek**
## Description
it's sorted by name now
Sorting by creation date is developed but not deployed yet. Followup https://github.com/aeternity/ae_mdw/issues/1572
As a hotfix for https://github.com/aeternity/aescan/pull/504

## Demo
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] change sorting of nfts in,list

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
I'm observing that sorting by name sometimes does not happen. For example, on page 2 we see NFTs with names starting with b and c, which should be on the first page. 
And also sorting NFTs with the name "test", I see it on the first page, and similar NFTs with the same name are on subsequent pages. 
@janmichek is it ok? 

https://github.com/aeternity/aescan/assets/69896204/88d3ef5b-aa56-4ac2-a29e-023ba6ee0c42

**Comment by janmichek** [comment]
> I'm observing that sorting by name sometimes does not happen. For example, on page 2 we see NFTs with names starting with b and c, which should be on the first page. And also sorting NFTs with the name "test", I see it on the first page, and similar NFTs with the same name are on subsequent pages. @janmichek is it ok?
> 2023-09-13.3.50.32.mov

Thanks for reporting, absolutely not ok.
I set the bug issue for MDW https://github.com/aeternity/ae_mdw/issues/1588
@michele-franchi let us know how you want to proceed.

**Review by michele-franchi — APPROVED** [review]
The ordering is still not ok because we should order NFTs by creation date but at least it's better then before, I would proceed with this until mdw implements the correct ordering.

**Review by lukeromanowicz — APPROVED** [review]
I agree with Michele

**Pull request merged**
