### PR TITLE
feat: Update npm packages

### LINKED ISSUE #614: Update npm packages
### Describe the solution you'd like

Update all npm packages to the latest stable version.

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #614

## Demo
The whole app is affected. The functionality should be the same. Needs extensive testing

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] upgrade all dependencies

### CODE REVIEW

**Comment by janmichek** [comment]
There are some following actions that needs to be done after merge https://github.com/aeternity/aescan/issues/625

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
Previous button becomes unavailable in In Auctions names tab, but this should be fixed separately:
https://github.com/aeternity/aescan/assets/69896204/2b957f58-d17c-4d73-9eff-0298d9e87f52

When I'm checking tokens for chosen account the previous button becomes unavailable. It's working on product: 
https://github.com/aeternity/aescan/assets/69896204/23b8856b-2ac6-4d95-b348-812cfa3c4578

@janmichek please check it

**Comment by Liubov-crypto** [comment]
Fixed, LGTM.

**Review by michele-franchi — APPROVED** [review]
Looks good

**Pull request merged**
