### PR TITLE
feat: Network unavailability handling

### LINKED ISSUE #95: Network unavailability handling
Let user know something went wrong and provide helpful action

Now it just looks 'broken'
- unstable internet connection
- node is down
- coingecko is down
- mdw is down

anything else?

Suggested by @janmichek.

Example of a problem we want to solve here: https://github.com/aeternity/aescan/issues/127

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #95

## Demo
image

https://github.com/aeternity/aescan/assets/15363559/153ea9ba-23db-4338-b798-8ac814752d2d

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)

### CODE REVIEW

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Review by michele-franchi — APPROVED** [review]
Simple and effective, LGTM

**Comment by Liubov-crypto** [comment]
> > LGTM
> > But I'm seeing a lil bit different text, is it ok?
> > off
> 
> What you would expect to read? What situation caused this label to show?

On screen you provided was info about Market cap data. I turned off the internet connection, so probably this is expected result.

**Comment by janmichek** [comment]
> > > LGTM
> > > But I'm seeing a lil bit different text, is it ok?
> > > off
> > 
> > 
> > What you would expect to read? What situation caused this label to show?
> 
> On screen you provided was info about Market cap data. I turned off the internet connection, so probably this is expected result. Just wanted to be sure.

Yep, that's expected behavior

**Pull request merged**
