### PR TITLE
feat: Token events counter

### LINKED ISSUE #63: Token events counter
### Please describe the problem that your request should resolve.
Display missing counter for Token events

### Describe the solution you'd like
Just connect an endpoint to generic UI

### Is it already possible to achieve the same outcome in any other way? If so, how?
Once this will be deployed and new endpoint exposed, we can implement it on frontned
https://github.com/aeternity/ae_mdw/issues/1264

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #63 

## Demo
firefox_4jYUqLpd85

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add token events counter

### CODE REVIEW

**Review by lukeromanowicz — APPROVED** [review]
Really nice, great stuff :rocket:

**Review by michele-franchi — APPROVED** [review]
Great job 👏

**Review by Liubov-crypto — APPROVED** [review]
From time to time I got 500 error, probably not related to this pr: 

500m

The rest, LGTM.

**Comment by janmichek** [comment]
@Liubov-crypto Can you provide the link?

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto Can you provide the link?

What do you mean? I have used link from this pr. 
I see that mainnet is returned 500 error.

**Comment by janmichek** [comment]
The token / contract id

**Comment by Liubov-crypto** [comment]
> https://pr-456-aescan.stg.aepps.com

WTT: ct_KeTvHnhU85vuuQMMZocaiYkPL9tkoavDRT3Jsy47LK2YqLHYb

**Pull request merged**
