### PR TITLE
feat: Display all testnet tokens

### LINKED ISSUE #732: Display all testnet tokens
**Acceptance criteria:**
- On testnet all tokens in the /tokens page are visible
- The dropdown "Listed" / "All tokens" is hidden
- If the token name is empty (also in the details page):
  - A gray text "Empty name" is displayed
- If the token symbol is empty (also in the details page):
  - A gray text "Empty symbol" is displayed

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #732

## Demo

image

image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] disable listed tokens for testnet
- [x] add N/A labels

### CODE REVIEW

**Comment by janmichek** [comment]
as folowup I created this https://github.com/aeternity/aescan/issues/742

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
I think there is an issue, total supply is missing for some tokens: 

comm

https://github.com/aeternity/aescan/assets/69896204/7a1e99f1-f08c-4ded-b2d3-9bd25efe71d3

I can't see holders, probably some issues with backend: 

backend

**Comment by janmichek** [comment]
@Liubov-crypto all fixed, thanks for testing

**Comment by Liubov-crypto** [comment]
I have a question: is total supply and Amount of the tokens held by its owner shouldn't be the same? 
https://github.com/aeternity/aescan/assets/69896204/f5f977a9-79fd-416e-bff7-a75ce9402873

if the one account is holding all amount of tokens, then percentage field should be 100%? 


https://github.com/aeternity/aescan/assets/69896204/804bd412-a2ed-4268-b096-20089cb28035


for example I can see Percentage on mainnet: 


https://github.com/aeternity/aescan/assets/69896204/e3cb2a8c-701d-4b40-b183-abadcc49453e

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
@janmichek please check it

**Comment by michele-franchi** [comment]
> I have a question: is total supply and Amount of the tokens held by its owner shouldn't be the same? https://github.com/aeternity/aescan/assets/69896204/f5f977a9-79fd-416e-bff7-a75ce9402873
> 
> if the one account is holding all amount of tokens, then percentage field should be 100%?
> 
>  2024-04-30.3.19.57.mov 
> for example I can see Percentage on mainnet:
> 
>  2024-04-30.3.24.15.mov

@janmichek did you already fix this issue?

**Comment by janmichek** [comment]
> > I have a question: is total supply and Amount of the tokens held by its owner shouldn't be the same? https://github.com/aeternity/aescan/assets/69896204/f5f977a9-79fd-416e-bff7-a75ce9402873
> > if the one account is holding all amount of tokens, then percentage field should be 100%?
> > 2024-04-30.3.19.57.mov
> > for example I can see Percentage on mainnet:
> > 2024-04-30.3.24.15.mov
> 
> @janmichek did you already fix this issue?

Nope, there is some delicate bug :D it appears on PR preview, but works on localhost.

**Comment by janmichek** [comment]
Can we continue on the review here? https://github.com/aeternity/aescan/pull/783 I could not make it right here

**Pull request closed without merging**
