### PR TITLE
feat: oracle details last query not displayed

### LINKED ISSUE #329: oracle details: last query not displayed
### Context information

application version: latest dev deployment
device: 
browser: 
operating system: 

### What is expected?
There should be an info about the last query.

### What is actually happening?
No info about last query is shown.
- https://aescan.dev.aepps.com/oracles/ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc
image

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #329

## Demo
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add time values to events
- [x] fix last queried time events

### CODE REVIEW

**Review by lukeromanowicz — APPROVED** [review]
Fantastic, looks and works great! :rocket:

**Comment by CharisSiarampalis** [comment]
@janmichek Some oracles have no data. Is this normal?
image

**Comment by lukeromanowicz** [comment]
Yes, it's possible that somebody registered an oracle but it hasn't been used.

**Review by CharisSiarampalis — APPROVED** [review]

**Comment by janmichek** [comment]
> The implementation looks good but I found two issues:
> 
>     * When you expand the response there are these two grey lines under "Queried At" and "Responded At" columns:
> 
> 
> image
> 
>     * "Queried At" and "Responded At" columns should have the same format of other height and time columns, in two rows. I know Danilo is pushing this forward in the design but in my opinion it does not make sense to have it in one line just in one table. We should handle this change for the entire app. For now I would suggest to use the existing one.

Right, fixed

**Comment by lukeromanowicz** [comment]
The issue @michele-franchi is not caused by this PR and it's already fixed in https://github.com/aeternity/aescan/pull/486

**Pull request merged**
