### PR TITLE
feat: All Hints revision

### LINKED ISSUE #240: Naming differences
### Context information
does not apply

### Steps to reproduce

https://github.com/aeternity/aescan/assets/15363559/96632bbe-5bb7-4903-a974-a45a704a3708

### What is expected?
Same naming

### What is actually happening?
different naming

Would good to go through the app and doublecheck everything

### LINKED ISSUE #307: All Hints revision
### Please describe the problem that your request should resolve.
Once we have all Hint-related issues merged, would be good to take a final look again.

### Describe the solution you'd like
- [ ] #411
- [ ] add references to the protocol. For example a link [Learn more](https://github.com/aeternity/protocol/blob/7172e2c2bfcb13d8d77276ec6025cb8fffa2b4a7/channels/ON-CHAIN.md#channel_snapshot_solo), with transactions that can be linked from the protocol repo.
- [x] Go through all the hints. We may find some misalignments, because we were creating it on the go gradually. Both in implementation and content
- [x] replace `Estimated date, time, and block height` with `Block height and estimated date and time`
- [x] doublecheck casing of Entities ?
- [x] Recieve final feedback from Marco and Philipp for all hints.
- [x] hint icon can still be few pixels above
- [x] wording Was vs Has been
- [x] links in toolips are unreachable, it closes when losing focus (regression)
- [x] check if the labels in listing match the ones in details of corresponding entity

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #307 
resolves #240 (Naming differences of labels)

## Demo
changes on many places

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change requires a change to the documentation.
- [x] fix spelling
- [x] unify labels listing vs detail

### CODE REVIEW

**Review by lukeromanowicz — APPROVED** [review]
Fair changes. Seems perfect to me. Very nice job :clap:

**Comment by lukeromanowicz** [comment]
I suggest to include Marco and Charis in the reviewers

**Comment by janmichek** [comment]
> I suggest to include Marco and Charis in the reviewers

I will once our reviews are done

**Comment by janmichek** [comment]
I set and wiki page Wording guide https://github.com/aeternity/aescan/wiki/Wording-guide . Feel free to extend over time

**Review by michele-franchi — APPROVED** [review]
Good job 👏

**Comment by janmichek** [comment]
@marc0olo Could you help us to check, please?

**Review by CharisSiarampalis — APPROVED** [review]

**Pull request merged**
